services:
  tailscale:
    container_name: tailscale
    hostname: tailscale
    image: tailscale/tailscale:latest
    volumes:
      - data:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    privileged: true
    restart: unless-stopped

volumes:
  data:
