services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_SERVER_URL: $MINIO_SERVER_URL
      MINIO_BROWSER_REDIRECT_URL: $MINIO_BROWSER_REDIRECT_URL
    env_file:
      - stack.env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./:/data
    command: "server /data --console-address ':9001'"
    restart: unless-stopped
